# Generated by Django 2.2.1 on 2019-05-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190504_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_updated']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_created',
        ),
    ]
